"""Static validation for workflow-program source.

The program is generated by our own planner, not by an adversary, so this is a
cooperative sandbox. The job is to stop the model from reaching outside the
primitive surface by accident: no imports, no file or process access, no dunder
escapes. It is the boundary guard. Past it, the restricted namespace in
``runtime.py`` is trusted.

Validation is a pure function of the source string. It does not execute
anything, so the planner can pre-flight generated code cheaply and the runner
can gate on the same verdict.
"""

from __future__ import annotations

import ast

from agent_fleet.orchestration.program.models import ProgramValidation

# Builtins the program may name. Everything else resolves to a NameError at
# runtime because the namespace omits it; listing the safe set here also lets
# the planner know what it is allowed to lean on.
SAFE_BUILTINS: frozenset[str] = frozenset(
    {
        "len", "range", "enumerate", "sorted", "reversed", "min", "max", "sum",
        "abs", "round", "str", "int", "float", "bool", "list", "dict", "set",
        "tuple", "frozenset", "zip", "map", "filter", "any", "all", "isinstance",
        "repr", "format", "type", "next", "iter", "slice", "divmod", "pow",
    }
)

# Primitive surface the runner injects. The first five are the static set; the
# last three are the dynamic-control primitives (Unit 4) that let a running
# program re-plan a loop, branch on a model judgment, or generate and run a
# bounded sub-program at runtime. All eight are plain names in the namespace, so
# none of them widens the escape surface below.
PRIMITIVES: frozenset[str] = frozenset(
    {"agent", "parallel", "pipeline", "phase", "log", "replan", "branch", "subprogram"}
)

# The subset that dispatches work indirectly: a program built only out of these
# still orchestrates agents, just one level down, so it must not be rejected as
# dispatching nothing.
_DYNAMIC_DISPATCH: frozenset[str] = frozenset({"replan", "branch", "subprogram"})

# Calls that must never appear, even though the namespace already omits them.
# Defense in depth, and a clearer error than a bare NameError.
_FORBIDDEN_CALLS: frozenset[str] = frozenset(
    {
        "eval", "exec", "compile", "open", "__import__", "input", "breakpoint",
        "globals", "locals", "vars", "getattr", "setattr", "delattr", "hasattr",
        "memoryview", "exit", "quit", "help",
    }
)

_FORBIDDEN_NODES: tuple[type[ast.AST], ...] = (
    ast.Import,
    ast.ImportFrom,
    ast.Global,
    ast.Nonlocal,
    ast.AsyncFunctionDef,
    ast.Await,
    ast.AsyncFor,
    ast.AsyncWith,
    ast.With,
    ast.Yield,
    ast.YieldFrom,
)


class _Checker(ast.NodeVisitor):
    def __init__(self) -> None:
        self.errors: list[str] = []
        self.agent_calls = 0
        self.uses_parallel = False
        self.uses_pipeline = False
        self.uses_dynamic = False

    def _fail(self, node: ast.AST, msg: str) -> None:
        line = getattr(node, "lineno", "?")
        self.errors.append(f"line {line}: {msg}")

    def generic_visit(self, node: ast.AST) -> None:
        if isinstance(node, _FORBIDDEN_NODES):
            self._fail(node, f"{type(node).__name__} is not allowed in a workflow program")
            return
        super().generic_visit(node)

    def visit_Attribute(self, node: ast.Attribute) -> None:
        if node.attr.startswith("_"):
            self._fail(node, f"access to dunder/private attribute '.{node.attr}' is not allowed")
        self.generic_visit(node)

    def visit_Name(self, node: ast.Name) -> None:
        if node.id.startswith("__") and node.id.endswith("__"):
            self._fail(node, f"reference to dunder name '{node.id}' is not allowed")
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        func = node.func
        if isinstance(func, ast.Name):
            if func.id in _FORBIDDEN_CALLS:
                self._fail(node, f"call to '{func.id}()' is not allowed")
            elif func.id == "agent":
                self.agent_calls += 1
            elif func.id == "parallel":
                self.uses_parallel = True
            elif func.id == "pipeline":
                self.uses_pipeline = True
            elif func.id in _DYNAMIC_DISPATCH:
                self.uses_dynamic = True
        self.generic_visit(node)


def validate_workflow_program(source: str) -> ProgramValidation:
    """Validate program source without executing it.

    Returns a verdict carrying any errors plus a small profile of the program
    (how many ``agent()`` calls, whether it fans out). A program with zero
    ``agent()`` calls is rejected: a workflow that dispatches nothing is a bug,
    not an orchestration.
    """
    try:
        tree = ast.parse(source, mode="exec")
    except SyntaxError as exc:
        return ProgramValidation(ok=False, errors=(f"syntax error: {exc.msg} (line {exc.lineno})",))

    checker = _Checker()
    checker.visit(tree)

    errors = list(checker.errors)
    if checker.agent_calls == 0 and not checker.uses_pipeline and not checker.uses_dynamic:
        errors.append(
            "program dispatches no agents "
            "(no agent()/pipeline()/branch()/replan()/subprogram() call)"
        )

    return ProgramValidation(
        ok=not errors,
        errors=tuple(errors),
        agent_calls=checker.agent_calls,
        uses_parallel=checker.uses_parallel,
        uses_pipeline=checker.uses_pipeline,
        uses_dynamic=checker.uses_dynamic,
    )
