"""Format PR analysis as GitHub markdown comment."""

from __future__ import annotations

import textwrap
from typing import Any


def _severity_emoji(severity: str) -> str:
    return {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}.get(severity, "⚪")


def _area_badge(area: str) -> str:
    badges = {
        "security": "🔒",
        "performance": "⚡",
        "frontend": "🎨",
        "backend": "⚙️",
        "pipeline": "📊",
        "data": "🗄️",
        "ops": "🖥️",
        "breaking": "💥",
        "tests": "🧪",
    }
    return badges.get(area.lower(), "📌")


def _group_findings(findings: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    groups: dict[str, list[dict[str, Any]]] = {}
    for finding in findings:
        severity = str(finding.get("severity", "low")).lower()
        groups.setdefault(severity, []).append(finding)
    return groups


def format_comment(
    analysis: dict[str, Any],
    *,
    title: str = "Composer PR Analysis",
    footer: str = "Generated by Agent Fleet PR analyzer (Composer 2.5)",
) -> str:
    risk_emoji = _severity_emoji(str(analysis.get("risk_level", "low")))
    recs = analysis.get("recommendations") or {}

    def check(value: bool) -> str:
        return "✅" if value else "⬜"

    primary = ", ".join(analysis.get("primary_areas") or [])
    findings_groups = _group_findings(analysis.get("findings") or [])
    findings_md = "_No findings — clean PR!_\n"
    if findings_groups:
        findings_md = ""
        for severity in ("critical", "high", "medium", "low"):
            items = findings_groups.get(severity)
            if not items:
                continue
            findings_md += (
                f"\n<details open>\n<summary>{_severity_emoji(severity)} "
                f"<b>{severity.upper()}</b> ({len(items)})</summary>\n\n"
            )
            findings_md += "| # | Area | Finding |\n|---|------|---------|\n"
            for index, item in enumerate(items, 1):
                area = str(item.get("area", "general"))
                message = str(item.get("message", "")).replace("|", "\\|")
                findings_md += f"| {index} | {_area_badge(area)} {area} | {message} |\n"
            findings_md += "</details>\n"

    suggestions = analysis.get("suggestions") or []
    suggestions_md = ""
    if suggestions and suggestions != ["none"]:
        suggestions_md = "\n### Suggestions\n| # | Suggestion |\n|---|------------|\n"
        for index, suggestion in enumerate(suggestions, 1):
            message = str(suggestion).replace("|", "\\|")
            suggestions_md += f"| {index} | {message} |\n"
        suggestions_md += "\n"

    checklist = analysis.get("methodology_checklist") or {}
    checklist_md = ""
    if checklist:
        checklist_md = (
            "\n### Methodology Checklist\n| Check | Status | Detail |\n|-------|--------|--------|\n"
        )
        for label, status_key, detail_key in (
            ("Integration tests", "integration_tests_present", "integration_tests_detail"),
            ("Error paths tested", "error_paths_tested", "error_paths_detail"),
            (
                "Cross-system contracts",
                "cross_system_contracts_verified",
                "cross_system_detail",
            ),
            ("Debug code removed", "debug_code_removed", "debug_code_detail"),
            ("Type checking verified", "type_checking_verified", "type_checking_detail"),
        ):
            status = bool(checklist.get(status_key, False))
            detail = str(checklist.get(detail_key, ""))[:100]
            icon = "✅" if status else "❌"
            checklist_md += f"| {label} | {icon} | {detail} |\n"
        checklist_md += "\n"

    return textwrap.dedent(f"""\
        ## 🤖 {title}

        **PR Type:** `{analysis.get("pr_type", "unknown")}`
        **Primary Areas:** {primary or "n/a"}
        **Risk Level:** {risk_emoji} {str(analysis.get("risk_level", "unknown")).upper()}
        > {analysis.get("risk_reasoning", "")}

        ### Summary
        {analysis.get("summary", "No summary provided.")}

        ### Recommended Checks
        | Check | Needed? |
        |-------|---------|
        | Frontend | {check(bool(recs.get("frontend_check")))} |
        | Backend | {check(bool(recs.get("backend_check")))} |
        | Pipeline | {check(bool(recs.get("pipeline_check")))} |
        | Security | {check(bool(recs.get("security_check")))} |
        | QA / Testing | {check(bool(recs.get("qa_check")))} |
        | Performance | {check(bool(recs.get("performance_check")))} |
        | Data | {check(bool(recs.get("data_check")))} |
        | Ops / Infra | {check(bool(recs.get("ops_check")))} |
        {checklist_md}
        ### Findings by Severity
        {findings_md}
        {suggestions_md}
        ### Deep Dive
        {str(analysis.get("deep_analysis") or "_No analysis provided._").strip()}

        ---
        *{footer}*
    """)
