"""GitHub Actions entrypoint for Agent Fleet PR analyzer."""

from __future__ import annotations

import os
import sys
import textwrap
from pathlib import Path

from agent_fleet.backends import make_backend
from agent_fleet.config import load_fleet_config
from agent_fleet.pr_review.analyzer import analyze_changes
from agent_fleet.pr_review.config import PrReviewConfig, load_pr_review_config
from agent_fleet.pr_review.format import format_comment
from agent_fleet.pr_review.git import (
    get_changed_files,
    get_diff,
    is_oversized_pr,
    is_trivial_pr,
)
from agent_fleet.pr_review.github import (
    load_github_event,
    resolve_pr_from_event,
    upsert_pr_comment,
)
from agent_fleet.repo import find_repo_config


def main() -> int:
    from agent_fleet.logging_config import configure_fleet_logging

    configure_fleet_logging()
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")
    if not token or not repo:
        print("Error: GITHUB_TOKEN and GITHUB_REPOSITORY required", file=sys.stderr)
        return 1

    backend_name = os.environ.get("AGENT_FLEET_BACKEND", "cursor").lower()
    if backend_name == "cursor" and not os.environ.get("CURSOR_API_KEY"):
        print("Error: CURSOR_API_KEY required for cursor backend", file=sys.stderr)
        return 1
    if backend_name == "kimi" and not os.environ.get("KIMI_API_KEY"):
        print("Error: KIMI_API_KEY required for kimi backend", file=sys.stderr)
        return 1

    event = load_github_event()
    pull_request = resolve_pr_from_event(event, repo, token)
    pr_number = int(pull_request["number"])
    base_sha = str(pull_request["base"]["sha"])
    head_sha = str(pull_request["head"]["sha"])

    workspace = Path(os.environ.get("AGENT_FLEET_WORKSPACE", Path.cwd())).resolve()
    repo_config = find_repo_config(workspace)
    raw = {}
    if repo_config:
        for name in (".agent-fleet.yaml", ".agent-fleet.yml"):
            path = repo_config.repo_root / name
            if path.exists():
                import yaml

                raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
                break
    pr_config = load_pr_review_config(repo_config.repo_root if repo_config else workspace, raw)
    if pr_config is None:
        pr_config = PrReviewConfig()

    fleet_config = load_fleet_config()
    backend = make_backend(fleet_config)

    cwd = repo_config.repo_root if repo_config else workspace
    files = get_changed_files(base_sha, head_sha, cwd=cwd)
    diff = get_diff(base_sha, head_sha, cwd=cwd)
    marker = pr_config.comment_title

    if is_trivial_pr(files, pr_config.trivial_patterns):
        body = textwrap.dedent(f"""\
            ## 🤖 {marker}

            Skipped — all changed files are docs, locks, or assets only.
        """)
        upsert_pr_comment(
            repo=repo,
            pr_number=pr_number,
            token=token,
            body=body,
            marker=marker,
        )
        return 0

    if is_oversized_pr(files, pr_config.oversized_threshold):
        body = textwrap.dedent(f"""\
            ## 🤖 {marker}

            Skipped — {len(files)} files changed (threshold {pr_config.oversized_threshold}).
            Split the PR or exclude generated/venv artifacts.
        """)
        upsert_pr_comment(
            repo=repo,
            pr_number=pr_number,
            token=token,
            body=body,
            marker=marker,
        )
        return 0

    analysis = analyze_changes(
        diff=diff,
        files=files,
        config=pr_config,
        backend=backend,
        workspace=cwd,
        pr_number=pr_number,
        model=fleet_config.default_model,
        timeout_s=fleet_config.timeout_seconds,
    )
    body = format_comment(
        analysis,
        title=pr_config.comment_title,
        footer=f"Generated by {pr_config.backend_label} ({fleet_config.default_model})",
    )
    upsert_pr_comment(
        repo=repo,
        pr_number=pr_number,
        token=token,
        body=body,
        marker=marker,
    )
    print(f"Posted analysis for PR #{pr_number}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
