"""Shared PR review runner for CLI, Hermes, and GitHub Actions."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

from agent_fleet.backends import make_backend
from agent_fleet.config import FleetConfig, load_fleet_config
from agent_fleet.pr_review.analyzer import analyze_changes
from agent_fleet.pr_review.config import PrReviewConfig
from agent_fleet.pr_review.format import format_comment
from agent_fleet.pr_review.git import get_working_tree_diff, is_oversized_pr, is_trivial_pr
from agent_fleet.pr_review.verdict import analysis_to_review_result, risk_to_verdict
from agent_fleet.repo import RepoConfig, find_repo_config, merge_repo_into_fleet_config

if TYPE_CHECKING:
    from agent_fleet.hooks import LLMBackend


def resolve_pr_review_config(repo: RepoConfig | None) -> PrReviewConfig:
    if repo and repo.pr_review:
        return repo.pr_review
    return PrReviewConfig()


def run_pr_review(
    *,
    workspace: Path,
    fleet_config: FleetConfig | None = None,
    base_branch: str = "main",
    pr_number: int = 0,
    backend: LLMBackend | None = None,
) -> dict[str, Any]:
    workspace = workspace.resolve()
    repo = find_repo_config(workspace)
    config = merge_repo_into_fleet_config(fleet_config or load_fleet_config(), repo)
    pr_config = resolve_pr_review_config(repo)
    engine = backend or make_backend(config)

    diff, files = get_working_tree_diff(cwd=workspace, base_branch=base_branch)
    if is_trivial_pr(files, pr_config.trivial_patterns):
        analysis = {
            "pr_type": "docs",
            "primary_areas": [],
            "risk_level": "low",
            "risk_reasoning": "Trivial PR — docs/locks/assets only.",
            "summary": "Skipped deep analysis for trivial file set.",
            "deep_analysis": "",
            "recommendations": {},
            "findings": [],
            "suggestions": [],
            "skipped": "trivial",
        }
    elif is_oversized_pr(files, pr_config.oversized_threshold):
        analysis = {
            "pr_type": "other",
            "primary_areas": [],
            "risk_level": "medium",
            "risk_reasoning": f"Too many files ({len(files)} > {pr_config.oversized_threshold}).",
            "summary": "PR exceeds analyzer file threshold.",
            "deep_analysis": "",
            "recommendations": {},
            "findings": [],
            "suggestions": ["Split PR or exclude generated artifacts."],
            "skipped": "oversized",
        }
    else:
        analysis = analyze_changes(
            diff=diff,
            files=files,
            config=pr_config,
            backend=engine,
            workspace=workspace,
            pr_number=pr_number,
            model=config.default_model,
            timeout_s=config.timeout_seconds,
            skill_dirs=list(config.skill_dirs),
        )

    review = analysis_to_review_result(analysis, pr_number=pr_number or 1)
    comment = format_comment(
        analysis,
        title=pr_config.comment_title,
        footer=f"Generated by {pr_config.backend_label} ({config.default_model})",
    )
    return {
        "analysis": analysis,
        "review": review.to_dict(),
        "verdict": review.verdict.value,
        "risk_level": analysis.get("risk_level", "low"),
        "risk_to_verdict": risk_to_verdict(
            str(analysis.get("risk_level", "low")),
            list(analysis.get("findings") or []),
        ).value,
        "comment_markdown": comment,
        "changed_files": files,
        "repo": repo.display_name if repo else workspace.name,
        "backend": config.default_backend,
        "model": config.default_model,
    }
